[package]
    name        = "scislide"
    version     = "0.1.0"
    entrypoint  = "scislide.typ"
    authors     = ["ivaquero"]
    license     = "MIT"
    description = "Template for Scientific Slides"
    repository  = ""
